# Generated by Django 5.1.15 on 2025-12-16 23:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_adult', models.BooleanField(default=False, help_text='Restricted to users 18+')),
                ('max_wishes_per_period', models.IntegerField(default=1, help_text='Maximum wishes that can be assigned from this category per period', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_days_to_complete', models.IntegerField(default=7, help_text='Minimum days given to complete a wish from this category', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_days_to_complete', models.IntegerField(default=30, help_text='Maximum days allowed to complete a wish from this category', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(help_text='Date by which the wish should be completed')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False, help_text='True if rejected in public mode')),
                ('assigned_to', models.ForeignKey(help_text='User who must fulfill this wish', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_wishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('private', 'Private (Couple)'), ('public', 'Public (Network)')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('private_period_days', models.IntegerField(blank=True, help_text='Custom period length for private matches (in days)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private_categories', models.ManyToManyField(blank=True, help_text='Categories agreed upon for private matches', to='wishes.category')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField()),
                ('proposed_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='wishes.assignment')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_negotiations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'negotiations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, help_text='Specific match for private periods, null for global public periods', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='wishes.match')),
            ],
            options={
                'db_table': 'periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='wishes.period'),
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text="Inactive wishes won't be assigned")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishes', to='wishes.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='wishes.wish'),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('completed_time', models.TimeField(blank=True, null=True)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment_by_creator', models.TextField(blank=True, help_text='Comment by the wish creator')),
                ('comment_by_executor', models.TextField(blank=True, help_text='Comment by the user who fulfilled the wish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='wishes.assignment')),
            ],
            options={
                'db_table': 'executions',
                'ordering': ['-completed_date'],
                'indexes': [models.Index(fields=['assignment'], name='executions_assignm_cff183_idx'), models.Index(fields=['completed_date'], name='executions_complet_3e6723_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', 'status'], name='matches_user1_i_380122_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', 'status'], name='matches_user2_i_003b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='negotiation',
            index=models.Index(fields=['assignment', 'status'], name='negotiation_assignm_80848d_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['start_date', 'end_date', 'is_active'], name='periods_start_d_f15236_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['match', 'is_active'], name='periods_match_i_d4d284_idx'),
        ),
        migrations.AddIndex(
            model_name='wish',
            index=models.Index(fields=['user', 'is_active'], name='wishes_user_id_7bdc34_idx'),
        ),
        migrations.AddIndex(
            model_name='wish',
            index=models.Index(fields=['category', 'is_active'], name='wishes_categor_857ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_to', 'is_completed'], name='assignments_assigne_0b7549_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['period', 'is_completed'], name='assignments_period__fb2571_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['wish'], name='assignments_wish_id_d299fd_idx'),
        ),
    ]
